baseURL = 'https://neffigie.dev/'
locale = 'en-US'
title = 'Anna Noelle'
disableKinds = ['taxonomy', 'term']

[params.social]
email = 'mailto:neffigie@gmail.com'
linkedin = 'https://www.linkedin.com/in/anna-noelle/'
github = 'https://github.com/neffigie'

[outputs]
home = ['html', 'rss']

[sitemap]
changeFreq = 'weekly'
filename = 'sitemap.xml'
priority = 0.5

[security]
allowContent = ['^text/html$']
